#cloud-config

users:
  - name: blipper
    groups: sudo, docker
    shell: /bin/bash
    sudo: [ 'ALL=(ALL) NOPASSWD:ALL' ]
    lock_passwd: true
    ssh_authorized_keys:
      - "{{SSH_PUBLIC_KEY}}"

groups:
  - docker

# Set timezone
timezone: Europe/London

runcmd:
  - |
    echo "BASIC_AUTH_USER={{BASIC_AUTH_USER}}" > /home/blipper/.initial-env
    echo "BASIC_AUTH_PASSWORD={{BASIC_AUTH_PASSWORD}}" >> /home/blipper/.initial-env
    su - blipper -c "curl -sSL https://raw.githubusercontent.com/ijpatricio/blipper/main/install/download.sh | bash"
    su - blipper -c "cd /home/blipper/blipper && ./install/install.sh"
